### ISSUE TITLE
No results for section with only Vx or Vy

### ISSUE THREAD

**Issue by MEMAndersen** [Kleissl/HollowRC#2]
The program yields no result when analyzing a cross section with with a load combination consisting of only Vx and/or Vy. 

The influence of Vx and Vy also does not seem to be present when adding torsion, only the results of the torsion are shown in the plot.

**Comment by Kleissl** [comment]
Thanks for pointing out this error! 
The issue have been corrected in the latest commit and will be included in the next release v1.1
